name: hitosea

version: 0.0.2
description: A command-line tool written in Dart
homepage: https://github.com/SyKingW/hitosea-command-tool-dart
repository: https://github.com/SyKingW/hitosea-command-tool-dart

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.7.0
  path: ^1.9.0

dev_dependencies:

executables:
  hitosea: # 这将创建全局可用的 `my-tool` 命令

